global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'my-app'
    static_configs:
      - targets: ['app-host:app-port']
  - job_name: 'nginx'
    metrics_path: /nginx_status
    static_configs:
      - targets: ['nginx:8080']
  - job_name: "node-exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']